security:
    providers:
        jwt:
            lexik_jwt:
                class: App\Security\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/wardrobe
            stateless: true
            anonymous: true
            provider: jwt
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/wardrobe, roles: [ROLE_USER] }
        - { path: ^/products, role: IS_AUTHENTICATED_ANONYMOUSLY }